### ISSUE TITLE
nextflow run nf-core/cutandrun error: Nextflow version 20.10.0 does not match workflow required version: >=20.11.0-edge

### ISSUE THREAD

**Issue by geng-lee** [nf-core/cutandrun#1]
### nextflow run nf-core/cutandrun --input samplesheet.csv -profile docker --genome GRCm38
N E X T F L O W  ~  version 20.10.0
Launching `nf-core/cutandrun` [tiny_agnesi] - revision: 45316032bc [master]
------------------------------------------------------
 nf-core/cutandrun v1.0dev
------------------------------------------------------

Core Nextflow options
    revision       : master
    runName        : tiny_agnesi
    containerEngine: docker
    launchDir      : /cut_tag/test
    workDir        : /cut_tag/test/work
    projectDir     : /home/.nextflow/assets/nf-core/cutandrun
    userName       : lee
    profile        : docker
    configFiles    : /home/.nextflow/assets/nf-core/cutandrun/nextflow.config

Input/output options
    input          : samplesheet.csv

Reference genome options
    genome         : GRCm38
    fasta          : s3://ngi-igenomes/igenomes//Mus_musculus/Ensembl/GRCm38/Sequence/WholeGenomeFasta/genome.fa

------------------------------------------------------

If you use nf-core/cutandrun for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.1400710

* The nf-core framework
  https://dx.doi.org/10.1038/s41587-020-0439-x
  https://rdcu.be/b1GjZ

* Software dependencies
  https://github.com/nf-core/cutandrun/blob/master/CITATIONS.md

------------------------------------------------------
Nextflow version 20.10.0 does not match workflow required version: >=20.11.0-edge

**Comment by MaxUlysse** [comment]
`cutanrun` requires `Nextflow` to be of at least `20.11.0-edge`, you're using `20.10.0`.

**Comment by geng-lee** [comment]
https://github.com/nextflow-io/nextflow/releases/tag/v20.10.0. 

Nextflow  20.11.0-edge is not available for download. How to get the download address?

**Comment by MaxUlysse** [comment]
have you tried `export NXF_VER=20.11.0-edge ; nextflow self-update`?

**Comment by MaxUlysse** [comment]
otherwise, it is available: https://github.com/nextflow-io/nextflow/releases/tag/v20.11.0-edge

**Comment by geng-lee** [comment]
### OK! 👌

### Thank you very much for your help！😁
