### ISSUE TITLE
Broad peak calling and DESeq2 for comparison of called peaks between conditions

### ISSUE THREAD

**Issue by dshechter** [nf-core/cutandrun#100]
### Description of feature

Two enhancements suggested:

1. add SEACR "relaxed" flag as an option and broadpeak for macs2
2. the nf-core chipseq pipeline uses DESeq2 to compare peaks between different conditions. I suggest adding this feature to the cutandrun pipeline.

**Comment by chris-cheshire** [comment]
Hi @dshechter, we can provide custom args for seacr no problem. The second point is more difficult as we took a decision in nf-core to not delve into downstream analysis - which DESEq2 is. We actually removed peak comparison from all of our pipelines as the purpose of the pipeline is to provide QC and upstream processing so a user can then easily load files up to R or Python and continue with their analysis.
