### ISSUE TITLE
WARNING: Skipping mount /local/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

### ISSUE THREAD

**Issue by ngocemy** [nf-core/cutandrun#122]
### Description of the bug

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRAGMENTS:BEDTOOLS_BAMTOBED
Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRAGMENTS:BEDTOOLS_BAMTOBED` terminated with an error exit status (140)

Command executed:

  bedtools \
      bamtobed \
      -bedpe \
      -i file_R3.mapped.sorted.bam \
      | bedtools sort > file_R3.bed
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRAGMENTS:BEDTOOLS_BAMTOBED":
      bedtools: $(bedtools --version | sed -e "s/bedtools v//g")
  END_VERSIONS

Command exit status:
  140

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /local/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

**Comment by chris-cheshire** [comment]
Has anyone else in your institute had singularity mount problems?

**Comment by chris-cheshire** [comment]
@ngocemy can i close this?
