### ISSUE TITLE
BOWTIE2_ALIGN step failed 

### ISSUE THREAD

**Issue by Lori-tan** [nf-core/cutandrun#125]
### Description of the bug

I had a problem running the pipeline. The test command `nextflow run nf-core/cutandrun -profile test,docker` works perfectly fine on my machine, but when I run the pipeline with my data, the alignment step failed with the following error message `[main_samview] fail to read the header from "-"` (Detailed message is showed in the section below).

It seems to me that the code below failed, so I tried to run the command manually on my machine with bowtie2 v2.4.5 and samtools v1.14 and it completed with no error.
```
bowtie2 \
      -x $INDEX \
      -1 igg_R1_1.trimmed.fastq.gz \
      -2 igg_R1_2.trimmed.fastq.gz \
      --threads 1 \
       \
      --end-to-end --very-sensitive --no-mixed --no-discordant --phred33 -I 10 -X 700 \
      2> igg_R1.target.bowtie2.log \
      | samtools view -@ 1  -bhS -o igg_R1.target.bam -
```
I tried to find out the version of Samtools that the pipeline used but failed to do so. I was using the Docker image pulled from https://hub.docker.com/r/nfcore/cutandrun/ by running docker pull nfcore/cutandrun:dev.

The data I used are DE_FoxA2_(20180205_MM_HsSc_0122MPM151) and DE_IgG_(20180205_MM_HsSc_0122MPM153) from [GSE126612](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126612).

I am not quite sure why this doesn't work in the pipeline. Could you please help me with this? Thanks very much!

### Command used and terminal output

```console
$ nextflow run nf-core/cutandrun -r 1.1 -name DE_FoxA2_test_2 -profile docker -work-dir path_to_work_dir -params-file nf-params.json

The pipeline report:

----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~\
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/cutandrun v1.1.0
----------------------------------------------------

Run Name: DE_FoxA2_test_2

####################################################
## nf-core/cutandrun execution completed unsuccessfully! ##
####################################################
The exit status of the task that caused the workflow execution to fail was: 1.
The full error message was:

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:ALIGN_BOWTIE2:BOWTIE2_ALIGN (igg_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:ALIGN_BOWTIE2:BOWTIE2_ALIGN (igg_R1)` terminated with an error exit status (1)

Command executed:

  INDEX=`find -L ./ -name "*.rev.1.bt2" | sed 's/.rev.1.bt2//'`
  bowtie2 \
      -x $INDEX \
      -1 igg_R1_1.trimmed.fastq.gz \
      -2 igg_R1_2.trimmed.fastq.gz \
      --threads 1 \
       \
      --end-to-end --very-sensitive --no-mixed --no-discordant --phred33 -I 10 -X 700 \
      2> igg_R1.target.bowtie2.log \
      | samtools view -@ 1  -bhS -o igg_R1.target.bam -
  
  if [ -f igg_R1.target.unmapped.fastq.1.gz ]; then
      mv igg_R1.target.unmapped.fastq.1.gz igg_R1.target.unmapped_1.fastq.gz
  fi
  if [ -f igg_R1.target.unmapped.fastq.2.gz ]; then
      mv igg_R1.target.unmapped.fastq.2.gz igg_R1.target.unmapped_2.fastq.gz
  fi
  
  cat <<-END_VERSIONS > versions.yml
  BOWTIE2_ALIGN:
      bowtie2: $(echo $(bowtie2 --version 2>&1) | sed 's/^.*bowtie2-align-s version //; s/ .*$//')
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
      pigz: $( pigz --version 2>&1 | sed 's/pigz //g' )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  [main_samview] fail to read the header from "-".
```

### Relevant files

[nextflow.log](https://github.com/nf-core/cutandrun/files/8734438/nextflow.log)

### System information

- Nextflow version: 22.04.1
- local
- Docker
- macOS Big Sur v11.6.4
- nf-core/cutandrun version: 1.1.0

**Comment by Lori-tan** [comment]
Oh ok. Should I repost this in the slack then? Or we could continue here? 

Here is the log file:
[defoxa2_R1.target.bowtie2.log](https://github.com/nf-core/cutandrun/files/8763990/defoxa2_R1.target.bowtie2.log)

**Comment by chris-cheshire** [comment]
No here is fine, thats a 137 error which is out of memory. Sounds like your genome is too large for alignment on your local computer. Do you have a more powerful computer you can run this on?

**Comment by Lori-tan** [comment]
> No here is fine, thats a 137 error which is out of memory. Sounds like your genome is too large for alignment on your local computer. Do you have a more powerful computer you can run this on?

When I ran the alignment manually with the same input as in the pipeline, it finished successfully. Is there a reason why it failed when running in the pipeline?

**Comment by Lori-tan** [comment]
You're right. This fixed the problem. Thanks a lot!

> Ah yes sorry I didnt see that comment. Then this is most likely a docker resource issue. start up the docker desktop dashboard and assign more resources to the engine
