### ISSUE TITLE
pipeline fail in NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS

### ISSUE THREAD

**Issue by blowinthesleep** [nf-core/cutandrun#132]
### Description of the bug

I use the cutandrun V2.0. it works well while using the test file. When I use the other data, it's show NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS.

### Command used and terminal output

```console
nextflow run nf-core/cutandrun -r 2.0 -profile singularity -params-file nf-params.json

the nf-params.json:
{
    "input": "test.csv",
    "outdir": "cuttag",
    "genome": "hg38",
    "bowtie2": "\/home\/rjz\/Zhitai\/Genomes\/Homo_sapiens\/UCSC\/hg38\/Sequence\/Bowtie2Index\/",
    "gtf": "\/home\/rjz\/Zhitai\/Genomes\/Homo_sapiens\/UCSC\/hg38\/annotation\/hg38.ncbiRefSeq.gtf",
    "spikein_bowtie2": "\/home\/rjz\/Zhitai\/Genomes\/Escherichia_coli_K_12_DH10B\/Ensembl\/EB1\/Sequence\/Bowtie2Index\/",
    "spikein_fasta": "\/home\/rjz\/Zhitai\/Genomes\/Escherichia_coli_K_12_DH10B\/Ensembl\/EB1\/Sequence\/WholeGenomeFasta\/genome.fa",
    "fasta": "\/home\/rjz\/Zhitai\/Genomes\/Homo_sapiens\/UCSC\/hg38\/Sequence\/WholeGenomeFasta\/genome.fa",
    "skip_trimming": true,
    "skip_removeduplicates": true,
    "peakcaller": "macs2",
    "max_cpus":12,
    "max_memory":"14GB"
}
```

### Relevant files

Error information:
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS` terminated with an error exit status (1)

Command executed:

  consensus_peaks.py \
      --peaks "*.peaks.bed" \
      --outpath .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS":
      python: $(python --version | grep -E -o "([0-9]{1,}\.)+[0-9]{1,}")
      numpy: $(python -c 'import numpy; print(numpy.__version__)')
      pandas: $(python -c 'import pandas; print(pandas.__version__)')
      upsetplot: $(python -c 'import upsetplot; print(upsetplot.__version__)')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'count'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/rjz/.nextflow/assets/nf-core/cutandrun/bin/consensus_peaks.py", line 75, in <module>
      peak_counts = upsetplot.from_memberships(cat_list, data = df_i['count'])
    File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
      raise KeyError(key) from err
  KeyError: 'count'

Work dir:
  /mnt/data/cuttag/work/66/9943b42cf673625faa38e8b513510e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/rjz/.nextflow/assets/nf-core/cutandrun/./workflows/cutandrun.nf' at line: 967 or see '.nextflow.log' file for more details

### System information

nextflow version 22.04.0.5697
Hardware:desktop
Container engine:Singularity
singularity version:singularity-ce version 3.10.0-focal
OS: ubuntu 20LTS
Version of nf-core/cutandrun: 2.0

**Comment by chris-cheshire** [comment]
hey thanks for your bug report - could you post your sample sheet please?

**Comment by blowinthesleep** [comment]
> hey thanks for your bug report - could you post your sample sheet please?

Of course! This is  my sample sheet. Thanks
```
group,replicate,fastq_1,fastq_2,control
igG,1,igG_rep1_1.fastq.gz,igG_rep1_2.fastq.gz,
igG,2,igG_rep2_1.fastq.gz,igG_rep2_2.fastq.gz,
H1K4me1,1,H1K4me1_rep1_1.fastq.gz,H1K4me1_rep1_2.fastq.gz,igG
H1K4me1,2,H1K4me1_rep2_1.fastq.gz,H1K4me1_rep2_2.fastq.gz,igG
H1K4me2,1,H1K4me2_rep2_1.fastq.gz,H1K4me2_rep2_2.fastq.gz,igG
H1K4me2,2,H1K4me2_rep2_1.fastq.gz,H1K4me2_rep2_2.fastq.gz,igG
H1K4me3,1,H1K4me3_rep1_1.fastq.gz,H1K4me3_rep1_2.fastq.gz,igG
H1K4me3,2,H1K4me1_rep2_1.fastq.gz,H1K4me1_rep2_2.fastq.gz,igG
```

**Comment by blowinthesleep** [comment]
> hey thanks for your bug report - could you post your sample sheet please?

I have noticed that there are some WARNING message when I launch the pipeline. 
```
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:SEACR_CALLPEAK -- Did you mean: NFCORE_CUTANDRUN:CUTANDRUN:MACS2_CALLPEAK?
WARN: There's no process matching config selector: .*PREPARE_GENOME:GUNZIP_.*
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_GENOME:UNTAR_.*
```
Does those WARNING message make the pipeline failure?

**Comment by chris-cheshire** [comment]
No the warnings dont mean anything but I am trying to remove them

**Comment by chris-cheshire** [comment]
I will analyse this and get back to you
