### ISSUE TITLE
Add option for SEACR "relaxed" mode

### ISSUE THREAD

**Issue by stfacc** [nf-core/cutandrun#133]
### Description of feature

In case, I think I can prepare a PR with some guidance.

Would you prefer something like `--seacr_mode [stringent|relaxed]` with a `stringent` default, or a boolean switch like `--seacr_relaxed`?

Or maybe add a new mode `SEACR_RELAXED` to `--peakcaller`? this would allow to run both, and choose one for further analysis

**Comment by chris-cheshire** [comment]
You can run SEACR with custom parameters using an extra config file. I try to avoid over parameterization if I can
