### ISSUE TITLE
Accelerate the frip.py

### ISSUE THREAD

**Issue by blowinthesleep** [nf-core/cutandrun#136]
### Description of feature

During the frip process, the frip.py uses only 2 cores and less than 1G RAM. Could frip.py use more resources to get less analysis time?

**Comment by chris-cheshire** [comment]
Hi, are you using version 2 of the pipeline? We were getting problems running `cr = crpb.CountReadsPerBin([bam_file], bedFile=[peak_file_list[idx]], numberOfProcessors=int(1))` with more an one processor so we have now had to pin it to 1. If you have any suggestions of how to make line of code work then we can increase the number of cores for frip

**Comment by chris-cheshire** [comment]
I will add this to the work schedule for the next release

**Comment by blowinthesleep** [comment]
> Hi, are you using version 2 of the pipeline? We were getting problems running `cr = crpb.CountReadsPerBin([bam_file], bedFile=[peak_file_list[idx]], numberOfProcessors=int(1))` with more an one processor so we have now had to pin it to 1. If you have any suggestions of how to make line of code work then we can increase the number of cores for frip

I saw some pipelines use the R script to calculate the frip score. I know whether the R script is more suitable than python package.

**Comment by blowinthesleep** [comment]
> Hi, are you using version 2 of the pipeline? We were getting problems running `cr = crpb.CountReadsPerBin([bam_file], bedFile=[peak_file_list[idx]], numberOfProcessors=int(1))` with more an one processor so we have now had to pin it to 1. If you have any suggestions of how to make line of code work then we can increase the number of cores for frip

if I choose the seacr, the frip usually fail because of the Process exceeded running time limit (4h)

**Comment by chris-cheshire** [comment]
Ok thanks - do you have a link to the R script for frip?

**Comment by blowinthesleep** [comment]
> Ok thanks - do you have a link to the R script for frip?

>https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-e6nvw93x7gmk/v1?step=22
 I saw this script of R. In this script, the author use the R package(chromVAR) to calculate this score. I have tried this script, it's   fast.
