### ISSUE TITLE
Fix - Failed to invoke `workflow.onComplete` event handler

### ISSUE THREAD

**Issue by chris-cheshire** [nf-core/cutandrun#137]
### Description of the bug

`Failed to invoke `workflow.onComplete` event handler`

**Comment by ShannonTown** [comment]
Hi, I still encounter this issue, after running
`nextflow self-update`

How do I update the cutandrun pipeline? It's not very clear [here](https://nf-co.re/cutandrun/2.0) at step 3 

The command I used is 
`nextflow run nf-core/cutandrun --input samplesheet.csv --outdir ./nf-core --genome dm6 -profile docker --skip_trimming -bg`

Thank you!!

**Comment by chris-cheshire** [comment]
please read the nextflow documentation on updating pipelines, its quite clear. You are updating nextflow itself with that command. Run `nextflow pull nf-core\cutandrun`

![image](https://user-images.githubusercontent.com/2357039/186137679-744f4470-8f53-4885-b1a4-c8c7fdc7a47c.png)

**Comment by chris-cheshire** [comment]
you also need to run with `-r dev` as this is an unreleased version of the pipeline that has this fixed

**Comment by ShannonTown** [comment]
Got it. Thank you very much!
