### ISSUE TITLE
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT

### ISSUE THREAD

**Issue by MarionPerrier** [nf-core/cutandrun#142]
### Description of the bug

Hi !

I would like to use your pipeline to analyse some cutnrun data.
However, I encounter a bug, which is the following : 
```
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT (sample_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT (sample_R1)` terminated with an error exit status (137)

Command executed:

  bedtools \
      sort \
      -i sample_R1.bedGraph \
       \
      > sample_R1.sorted.bedGraph
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT":
      bedtools: $(bedtools --version | sed -e "s/bedtools v//g")
  END_VERSIONS

Command exit status:
  137

Command output:
  (empty)

Command error:
  .command.sh: line 6:    28 Killed                  bedtools sort -i sample_R1.bedGraph > sample_R1.sorted.bedGraph

Work dir:
  /home/user/programmes/work/12/4847756627a2edafe6d8537c0c32fb

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

When I try to do the test, I also encounter an error, but the pipeline still end successfully. However, I don't have the exact same output as it is in the nf-core results page's website : 
```
Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/user/.nextflow/assets/nf-core/cutandrun/./workflows/cutandrun.nf' at line: 967 or see '.nextflow.log' file for more details
```

I don't know if that is suppose to happen.

### Command used and terminal output

```console
nextflow run nf-core/cutandrun --input samplesheet.csv --outdir results_cutnrun --genome mm10 -profile docker

For the test : 

nextflow run nf-core/cutandrun -profile test,docker --outdir test_nfcore
```

### Relevant files

[nextflow_test.log](https://github.com/nf-core/cutandrun/files/9103204/nextflow_test.log)

I don't have right now the nextflow.log for the real try with my samples (and not the test), but I will edit my ticket as soon as I have it.
[EDIT] : It is here : 
[nextflow_realData.log](https://github.com/nf-core/cutandrun/files/9118703/nextflow_realData.log)

I also give you the multiqc report for the test so you can see the difference
[multiqc.zip](https://github.com/nf-core/cutandrun/files/9103290/multiqc.zip)

### System information

- **nextflow version** : 22.04.4.5706
- **Hardware** : Desktop computer
- **Executor** : Local
- **Container engine** : Docker
- **OS** : Ubuntu 21.04
- **Version or nf-core/cutandrun** : v2.0.0

**Comment by chris-cheshire** [comment]
Hi thanks for your message - apologies for the slow response I have been away on holiday. Its always best to post these errors on the nf-core slack channels as they will get a faster response. 

Error 137 is an out of memory exception. Please assign more memory to bedtools sort using a custom config file. You can try 32.GB first. 

```
process {
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT' {
        cpus   = { check_max( 1     * task.attempt, 'cpus'    ) }
        memory = { check_max( 16.GB  * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h   * task.attempt, 'time'    ) }
    }
}
```

**Comment by MarionPerrier** [comment]
Hi,

Thank you a lot for your reply ! 
No worries for the delay, I was myself in holidays too.

By changing few parameters, I finally managed to run the pipeline entirely. 
Sadly, I don't have any results, and I suspect it to be linked to the problem I have while running the test pipeline.

I am moving on to slack with my new problem :) 

Thank you a lot for your time.
Marion
