### ISSUE TITLE
Add option for read extension to bedgraph (and subsequent bigwig) generation 

### ISSUE THREAD

**Issue by j-andrews7** [nf-core/cutandrun#150]
### Description of feature

The ability to extend the reads in bedgraph/bigWig generation results in "prettier" tracks. This can be done with the `-e` flag in the deeptools bamCoverage step (NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:DEEPTOOLS_BAMCOVERAGE). 

For example:
![image](https://user-images.githubusercontent.com/10225716/183696998-27fb8cbe-2b00-4e79-8f5f-fb130ff80ecd.png)

Pink is with no `-e` with a bin size of 10, teal and purple are with `-e` provided.

**Comment by chris-cheshire** [comment]
Hey @j-andrews7  - this has been included as a default in the `3.0` version of the pipeline
