### ISSUE TITLE
Add SEACR normalization and stringency options

### ISSUE THREAD

**Issue by CloXD** [nf-core/cutandrun#156]
### Description of feature

Hello, 
I'm working with some Cut and Tag data and with the kit that we are using ( iDEAL Cut&Tag Kit for Histones).
Since there is no spike-in genome in the library, I normalized using the CPM, as suggested in the reference.
Many of the peaks called using SEACR are very weak and the Igg have a signal that is very close to the samples ones.
I guess that in part it's due to the poor quality of the data ( we surely need to improve the library preparation ), but also I noticed that the hard-coded parameters SEACR disable their internal normalization and set the stringency to "stringent". In their github manual, they suggest to disable the normalization if the sample and control are normalized on each other. Since the CPM ( or any of the other methods included in the pipeline ) normalize against the input, I manually tried the internal normalization and the results are much better.
It would be nice to have those parameters explicitly defined in the pipeline.
I already created the repository with the additional parameters and I'm testing them now (https://github.com/CloXD/cutandrun ) as soon as I check that everything works nicely, I'll do the pull request.
Cheers,
Claudio

**Comment by chris-cheshire** [comment]
Hi, thanks for your suggestion! I have included these changes in the upcoming 3.0 release candidate. Keep an eye out for the announcement in the cutandrun slack channel.
