### ISSUE TITLE
Individual reads instead of fragments as SEACR input

### ISSUE THREAD

**Issue by CloXD** [nf-core/cutandrun#158]
### Description of the bug

Hello,
digging in the pipeline I noticed that the input of SEACR is the bedGraph generated using the bam of the individual reads rather than the fragments, as suggested in the README of SEACR github.
Is this a wanted behaviour? 
Cheers
Claudio

**Comment by CloXD** [comment]
I included the parameters in bedtools and deeptool in my fork https://github.com/CloXD/cutandrun that take in consideration the pair fragments

**Comment by chris-cheshire** [comment]
Hi not sure what you mean, fragments to me mean aligned reads in a BAM file. Also can you show me where you see the `-pc` option? I can't see it...

**Comment by CloXD** [comment]
Hello, 
sure: the fragment is the portion of the biological molecule between the beginning of the first read and the end of the second in pair-end. If you sequence in PE a fragment of 400 bp, for example, with the adapter at the end, you will get only the first and last 50 bp ( or 100, depending on the setting of your sequencer ). 
Both bedtools and deeptools have arguments that allow extending the paired-end reads to consider the fragment between the pairs as an actual signal ( -pc and --extendReads respectively ). 
The SEACR manual (https://github.com/FredHutch/SEACR) suggests indeed using the argument -bedpe of "bedtools bamtobed" in the conversion from BAM to bedGraph ( that is the same procedure used in the submodule CALCULATE_FRAGMENTS ), but doesn't allow to perform the normalization procedure that are done in PREPARE_PEAKCALLING. 

Probably this procedure is not essential in ChIP-seq, where the density of the reads is much higher and the fragments are smaller, but with the kit my lab is using ( iDEAL Cut & Tag ), the length of the fragments is around 900 bp and the differences are remarkable.
Let me know if I was clear enough and if my fork including this additional feature can be a good contribution to the community ( https://github.com/CloXD/cutandrun ).
Cheers,
Claudio

**Comment by chris-cheshire** [comment]
This is really interesting thank you, I suppose I did not realise that this was not the default operation of these programs.

So I guess from this there is no reason why we should not extend reads by default for both bamcoverage and genomecov?

**Comment by chris-cheshire** [comment]
By the way, I am not asking you to create a pull request from your fork because I have made significant changes to the pipeline for the `3.0` release and your changes may not merge properly so I am just copying them over where appropriate.

**Comment by CloXD** [comment]
You're welcome, this is the best part of being a community ;) 
I think you can set them as static parameters or, as I did in my fork, include an argument to disable this behaviour. 
Looking forward to seeing the new version!
Cheers,
Claudio
