### ISSUE TITLE
NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED error

### ISSUE THREAD

**Issue by gianfilippo** [nf-core/cutandrun#161]
### Description of the bug

Hi,

the analysis breaks at the BEDTOOLS_BAMTOBED  step.

I increased the memory (I hope), by using a custom config file, but it does not change the outcome. I think my config file is not doing what it is supposed to

Can you please help ?
Thanks

singularity {
    enabled = true
}

process {
    queue = 'general'
    executor = 'slurm'

    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT' {
        cpus   = { check_max( 20     * task.attempt, 'cpus'    ) }
        memory = { check_max( 118.GB  * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h   * task.attempt, 'time'    ) }
    }
}

params {
    max_memory = '118GB'
    max_cpus = 20
    max_time = '96h'
}

### Command used and terminal output

```console
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED (treatment_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED (treatment_R1)` terminated with an error exit status (137)

Command executed:

  bedtools \
      bamtobed \
      -bedpe \
      -i treatment_R1.sortedbyname.bam \
      | bedtools sort > treatment_R1.bed
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED":
      bedtools: $(bedtools --version | sed -e "s/bedtools v//g")
  END_VERSIONS

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  WARNING: Skipping mount /var/apptainer/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1124:11424:2049 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1140:9661:7138 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1142:21124:26271 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1143:26413:3208 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1146:14208:33677 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1156:15402:35524 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1201:16396:15577 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1207:26539:21903 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1230:15917:22138 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1319:20555:36652 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1336:25211:33974 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1337:13521:29105 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1345:4345:25394 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1349:1787:19116 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1361:23430:25755 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1371:6442:19163 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1401:3504:22060 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1412:20654:36918 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1420:4218:22294 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1431:12726:7122 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1452:15754:35415 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1506:24397:31501 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1507:28492:4836 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1522:30951:6277 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1528:4725:23015 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1532:6560:8500 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  *****WARNING: Query A00124:473:HNF3TDSX3:3:1548:8296:23437 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 
  .command.sh: line 6: 28838 Broken pipe             bedtools bamtobed -bedpe -i treatment_R1.sortedbyname.bam
       28839 Killed                  | bedtools sort > treatment_R1.bed
```

**Comment by gianfilippo** [comment]
Hi,

thanks. Sorry about the delay, but I was out of town.

The .command.run shows #SBATCH --mem 12288M
It does not seem much. What do you think ?

**Comment by chris-cheshire** [comment]
Yeah you could try bumping the memory with a config file. Do you know how to do this? Also the new version of the pipeline `3.0` is just days away from release, you could wait and then try then?

**Comment by gianfilippo** [comment]
Hi,
thanks. I tried bumping the memory (see below). Does it look ok ?

Thanks

process {
    queue = 'general'
    executor = 'slurm'

    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_SORT' {
        cpus   = { check_max( 20     * task.attempt, 'cpus'    ) }
        memory = { check_max( 118.GB  * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h   * task.attempt, 'time'    ) }
    }
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED' {
        cpus   = { check_max( 20     * task.attempt, 'cpus'    ) }
        memory = { check_max( 118.GB  * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h   * task.attempt, 'time'    ) }
    }
}

**Comment by chris-cheshire** [comment]
remove the check max as you are specifying the memory directly.

**Comment by gianfilippo** [comment]
Hi,

thanks. I removed check max and it did go through. When I run the pipeline I still get an error (see ERRORS SECTION).
From what I can see. the peak caller (usingonly MACS2) generates .peaks.bed_summits.bed under 03_peak_calling/04_called_peaks/ and the 'consensus peak' seems to be expecting .peaks.bed files.

I also noticed that when I submit a job, not, I am getting the warnings below (see WARNINGS SECTION).

What do you think ?
Right now, I am rerunning after adding SEACR as peak caller, to see what happens.

Best


================= ERRORS SECTION =================
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'count'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/.nextflow/assets/nf-core/cutandrun/bin/consensus_peaks.py", line 75, in <module>
    peak_counts = upsetplot.from_memberships(cat_list, data = df_i['count'])
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'count'


================= WARNINGS SECTION =================
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_COMPUTEMATRIX_GENE
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_COMPUTEMATRIX_PEAKS
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_PEAKCALLING:BEDTOOLS_GENOMECOV
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS
WARN: There's no process matching config selector: .*PREPARE_GENOME:GUNZIP_.*
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_GENOME:UNTAR_.*
WARN: There's no process matching config selector: NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED

**Comment by gianfilippo** [comment]
UPDATE:
after rerunning I see the 03_peak_calling subdirs showing also the missing files corresponding the all samples (before some were missing).
I still get an error, but this time at NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS

This is not relevant as the error is earlier on, at the consensus peak call.
Somehow, with MACS2 alone, consensus peaks were empty
Using SEACR, I get one peak only, which causes the error down the line.

I have 3 samples and 3 controls and require only replicate_threshold=2

How can I not have common peaks ?

What do you think ?
Thanks

**Comment by chris-cheshire** [comment]
Ok so I am just about to release version 3 of the pipeline which may sort some of these issues. Second, please try and post on slack as I don't check these messages too often and other people can see whats being talked about. Join the slack channel and you will see the release post as well

**Comment by gianfilippo** [comment]
Thanks!

I will switch to Slack
