### ISSUE TITLE
Novice user question: Error at PLOT_CONSENSUS_PEAKS

### ISSUE THREAD

**Issue by Krutang** [nf-core/cutandrun#163]
Hi!
Firs time user here. I installed nextflow locally and set up my pipeline via the launcher. It gave me the json:

{
    "input": "\/home\/robka\/nextflow_test\/fresh_start_2022_10_12\/samplesheet_GFP_mergedperR_fastq.csv",
    "outdir": "\/home\/robka\/nextflow_test\/fresh_start_2022_10_12\/GFP_mainout",
    "genome": "BDGP6",
    "peakcaller": "macs2"
}

I ran it via:

nextflow run nf-core/cutandrun -r 2.0 -name GFP_main -profile docker -work-dir /home/robka/nextflow_test/fresh_start_2022_10_12/GFP_mainout/work -params-file nf-params.json

The pipeline seemed to do well, but I got an error message in the execution_report file (see big paste below). Do you think it is an installation error or are there simply no consensus peaks? I thought all the dependencies were taken care of by docker?

Thanks in advance and apologies for novice question.

Error message:

Workflow execution completed unsuccessfully!

The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS` terminated with an error exit status (1)

Command executed:

  consensus_peaks.py \
      --peaks "*.peaks.bed" \
      --outpath .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS":
      python: $(python --version | grep -E -o "([0-9]{1,}\.)+[0-9]{1,}")
      numpy: $(python -c 'import numpy; print(numpy.__version__)')
      pandas: $(python -c 'import pandas; print(pandas.__version__)')
      upsetplot: $(python -c 'import upsetplot; print(upsetplot.__version__)')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-46vinym3 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'count'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/robka/.nextflow/assets/nf-core/cutandrun/bin/consensus_peaks.py", line 75, in 
      peak_counts = upsetplot.from_memberships(cat_list, data = df_i['count'])
    File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
      raise KeyError(key) from err
  KeyError: 'count'

Work dir:
  /home/robka/nextflow_test/fresh_start_2022_10_12/GFP_mainout/work/ad/bc204a886709b98e83a6766a2a1855

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by wbszhu** [comment]
Hi, I have the same problem. And I am trying the latest version.

**Comment by wbszhu** [comment]
Hi,
I have tried the latest version. It still has problem.
The command
```
nextflow run nf-core/cutandrun \
 --input $1  -profile docker  \
 --genome mm10 \
 --use_control false \
 --outdir /home/wzxu/00.LZ/02.SE/ctresults \
 --peakcaller macs2 
```
The sheet
```
group,replicate,fastq_1,fastq_2,control
h3k4me1,1,/home/wzxu/00.LZ/00.data/SRR11953243_1.fastq.gz,/home/wzxu/00.LZ/00.data/SRR11953243_2.fastq.gz,
h3k4me1,2,/home/wzxu/00.LZ/00.data/SRR11953244_1.fastq.gz,/home/wzxu/00.LZ/00.data/SRR11953244_2.fastq.gz,
```
The Error
```
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS` terminated with an error exit status (1)

Command executed:

  consensus_peaks.py \
      --peaks "*.peaks.bed" \
      --outpath .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:CONSENSUS_PEAKS:PLOT_CONSENSUS_PEAKS":
      python: $(python --version | grep -E -o "([0-9]{1,}\.)+[0-9]{1,}")
      numpy: $(python -c 'import numpy; print(numpy.__version__)')
      pandas: $(python -c 'import pandas; print(pandas.__version__)')
      upsetplot: $(python -c 'import upsetplot; print(upsetplot.__version__)')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-yd5ze088 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended t the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'count'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/wzxu/.nextflow/assets/nf-core/cutandrun/bin/consensus_peaks.py", line 75, in <module>
      peak_counts = upsetplot.from_memberships(cat_list, data = df_i['count'])
    File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
      raise KeyError(key) from err
  KeyError: 'count'

Work dir:
  /home/wzxu/00.LZ/02.SE/work/4d/c64805a863dbcad320d909052c83df

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/wzxu/.nextflow/assets/nf-core/cutandrun/./workflows/cutandrun.nf' at line: 967 or see '.nextflow.log' file for more details

```

**Comment by wbszhu** [comment]
Even tried the data from different experiments. It seems not the data's wrong.

**Comment by chris-cheshire** [comment]
I would you mind re-posting this on the slack channel? thanks
