### ISSUE TITLE
Cannot find revision 3.0

### ISSUE THREAD

**Issue by cnluzon** [nf-core/cutandrun#165]
### Description of the bug

First of all, thanks for developing this pipeline :) useful stuff!

I am aware that it's only been a few hours since the revision `3.0` is released, so I am wondering if it is a matter of something that has not been updated yet somewhere downstream of the release, if it is an actual bug or I need a specific version of Nextflow, but I think I am running the latest one.

So I tried to run the revision 3.0 (see the command attached) and got the error:

```
Cannot find revision `3.0` -- Make sure that it exists in the remote repository `https://github.com/nf-core/cutandrun`
```

### Command used and terminal output

```console
nextflow run nf-core/cutandrun -profile uppmax --project "${pcode}" -r 3.0 \
        --input "design.csv" \
        --fasta "reference/mm9.fa" \
        --gtf "reference/genes.gtf" \
        --bowtie2 "reference/Bowtie2Index/" \
        --normalisation_mode CPM \
        --spikein_genome dm6 \
        --save_spikein_aligned \
        --peakcaller seacr,macs2 \
        --use_control \
        --macs_gsize 2620345972 \
        --outdir ./cutandrun \
        --blacklist "reference/blacklist.bed"


Output being:
N E X T F L O W  ~  version 22.10.0
Cannot find revision `3.0` -- Make sure that it exists in the remote repository `https://github.com/nf-core/cutandrun`
```

### System information

Running on Uppmax (CentOS, slurm executor).
Nextflow version: 

``` 
N E X T F L O W
version 22.10.0 build 5827
created 13-10-2022 06:01 UTC (08:01 CEST)
cite doi:10.1038/nbt.3820
http://nextflow.io
``` 
Trying to run `nf-core/cutandrun -r 3.0`

**Comment by chris-cheshire** [comment]
Hi yes its doing it for me too, how odd! Would you mind posting stuff like this in the slack channels so other people can comment? Cheers, Chris

**Comment by chris-cheshire** [comment]
Ahh its doing for me now - just needed a jog i think, try again
