### ISSUE TITLE
Add alternative mappers

### ISSUE THREAD

**Issue by IStevant** [nf-core/cutandrun#168]
### Description of feature

Dear developers,

similarly to the ChIP-seq pipeline, would it be possible to propose several mappers such as BWA or STAR instead of only Bowtie2?
I have to integrate several omics data and I would like them to be mapped with the same tool.

Best,

Isabelle

**Comment by chris-cheshire** [comment]
Hi sorry for the delay - yes I can add it to the features list but given we have just done a release it may be a while sorry.

**Comment by IStevant** [comment]
No problem, I will mix the mapping from ChIPseq pipeline with the peak calling from cut&run pipeline in the meantime.
