### ISSUE TITLE
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED ()'

### ISSUE THREAD

**Issue by HardingZhang** [nf-core/cutandrun#169]
### Description of the bug

I'm sorry to bother you, I've recently been plagued with a problem where when I run the pipeline, it keeps stopping at the bedtools step, as shown below. I checked the log and found that the program is trapped and cannot continue causing a timeout. I am somewhat at my wits end and would like to get some help from you.

### Command used and terminal output

```console
Pipeline completed with errors-
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED (CL2_R1)'

Caused by:
  Process exceeded running time limit (4h)

Command executed:

  bedtools \
      bamtobed \
      -bedpe \
      -i CL2_R1.sortedbyname.bam \
      | bedtools sort > CL2_R1.bed

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED":
      bedtools: $(bedtools --version | sed -e "s/bedtools v//g")
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)
```

### Relevant files

[nextflow.log](https://github.com/nf-core/cutandrun/files/10057197/nextflow.log)

**Comment by chris-cheshire** [comment]
Hi, you just need to extend the time for that process with a custom config file. Write a new file and call my `my.config`. Use the syntax below to change the time/cpu/mem for a target process. Then include the config using the command line switch `-c my.config`

```
process {
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED' {
            cpus   = 1
            memory = 6.GB
            time   = 12.h
        }
}
```

**Comment by HardingZhang** [comment]
> Hi, you just need to extend the time for that process with a custom config file. Write a new file and call my `my.config`. Use the syntax below to change the time/cpu/mem for a target process. Then include the config using the command line switch `-c my.config`
> 
> ```
> process {
>     withName: 'NFCORE_CUTANDRUN:CUTANDRUN:EXTRACT_FRAGMENTS:BEDTOOLS_BAMTOBED' {
>             cpus   = 1
>             memory = 6.GB
>             time   = 12.h
>         }
> }
> ```

I'm sorry I didn't reply in time, I managed to get over this hurdle with your guidance.  As a newbie, thank you for your help！
