### ISSUE TITLE
Grouped Heatmaps and summit heatmap

### ISSUE THREAD

**Issue by Danfoltz** [nf-core/cutandrun#173]
Dear developers, 
It would be helpful if, in addition to individual heatmaps output from deeptools/computeMatrix, the combined heatmaps for the groups specified in the sample sheet were also produced. 

Also, please specify (and output if not already done) the bed file used to produce the individual deeptools/heatmaps.  

Thanks,
Dan

**Comment by chris-cheshire** [comment]
Hi @Danfoltz so sorry for the delay. This has been implemented in release `3.1`
