### ISSUE TITLE
test on minimal dataset failes

### ISSUE THREAD

**Issue by Rhinogradentia** [nf-core/cutandrun#174]
### Description of the bug

test run (as suggested in usage docs) with test dataset fails in `nf-core/cutandrun/./workflows/../modules/local/linux/cut.nf` line 6 with following error message:
```
Jan-24 09:50:25.320 [main] ERROR nextflow.cli.Launcher - Module compilation error
- file : /nf-core/cutandrun/./workflows/../modules/local/linux/cut.nf
- cause: end of line reached within a simple string 'x' or "x" or /x/;
   solution: for multi-line literals, use triple quotes '''x''' or """x""" or /x/ or $/x/$ @ line 6, column 108.
   ularity_pull_docker_container ?
```
Which is this line https://github.com/nf-core/cutandrun/blob/dcaa4423d783017996c30302d16d772facb0da7e/modules/local/linux/cut.nf#L6 

### Command used and terminal output

```console
nextflow pull -r 3.0 https://github.com/nf-core/cutandrun.git
nextflow run nf-core/cutandrun -r 3.0 -profile test,singularity,cbe --outdir /users/nadine/cut_run/testDIR/ 
```

nextflow.log output:
```
[...]
Jan-24 09:50:25.320 [main] ERROR nextflow.cli.Launcher - Module compilation error
- file : /nf-core/cutandrun/./workflows/../modules/local/linux/cut.nf
- cause: end of line reached within a simple string 'x' or "x" or /x/;
   solution: for multi-line literals, use triple quotes '''x''' or """x""" or /x/ or $/x/$ @ line 6, column 108.
   ularity_pull_docker_container ?
```

### Relevant files

[nextflow.log](https://github.com/nf-core/cutandrun/files/10488875/nextflow.log)

### System information

```
$ nextflow -v
nextflow version 20.07.1.5412

(apptainer)
singularity version 
1.1.3-1.el7
```
- HPC
- slurm
- Singularity
- CentOS-7
- cutandrun version: 3.0

**Comment by maxulysse** [comment]
What is your Nextflow version?

**Comment by Rhinogradentia** [comment]
$ nextflow -v
nextflow version 20.07.1.5412

**Comment by maxulysse** [comment]
Can you try with a more recent version?
Manifest is listing at least `21.10.3`
https://github.com/nf-core/cutandrun/blob/master/nextflow.config#L284

**Comment by Rhinogradentia** [comment]
I don't know if this will be possible on the HPC I'm working on, but I will have a look.
Thanks.

**Comment by Rhinogradentia** [comment]
This was the solution - thank you for your help. 
It ran successfully with v22.10.1

Now I have another error - but this has nothing to do with this issue.....
