### ISSUE TITLE
Should I add "--dovetail" for bowtie2 alignment?

### ISSUE THREAD

**Issue by weishwu** [nf-core/cutandrun#176]
Is it better to add "--dovetail" to allow overlaps between the mates since this may be common in CUT&RUN reads?

**Comment by chris-cheshire** [comment]
hi, could you discuss this in the slack group so we can get feedback from other users? Many thanks!

**Comment by weishwu** [comment]
I signed in on Slack, but I don't have the channel. Could you pull me in?
