### ISSUE TITLE
Add GoPeaks for peak calling 

### ISSUE THREAD

**Issue by gartician** [nf-core/cutandrun#177]
### Description of feature

Hi nf-core cutandrun team,

I am interested in adding an additional peak caller to the cutandrun nextflow pipeline called [GoPeaks](https://github.com/maxsonBraunLab/gopeaks). Its main advantage over SEACR and MACS2 is that it calls peaks with sensible widths and has fewer false positive peaks. This can lead to better specificity when performing transcription factor motif analysis (e.g. HOMER) and finding differential peak (e.g. DESeq2). This feature also allows the nf-core cutandrun user base to have an additional tool to call peaks in their biological system of interest. 

I am happy to code this enhancement and initiate a pull request. I have been wanting contribute to nf-core for a while, and I may have found a great opportunity to start my journey. Thank you for your consideration and I look forward to hearing from you! 

Resources

[GoPeaks: histone modification peak calling for CUT&Tag](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02707-w)

**Comment by chris-cheshire** [comment]
Hi there!

Always happy to have new contributors. A third peak caller would also be welcome, please go ahead and add it and we can review the PR once you have completed it.
