### ISSUE TITLE
Not a valid path value type: java.util.LinkedHashMap

### ISSUE THREAD

**Issue by Gin-Wang** [nf-core/cutandrun#182]
### Description of the bug

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_GENOME:BOWTIE2_BUILD_TARGET (null)'

Caused by:
  Not a valid path value type: java.util.LinkedHashMap ([id:spikein_fasta])

I tried different type of spike in genome.fa file or file path but failed too

I have used similar pipeline successfully, such as nfcore/chipseq and nfcore/atacseq. Could you help me do this? Thx a lot!

### Command used and terminal output

```console
input
nextflow run $cutandrun --input /home/***/cuttag/samplesheet.csv --outdir  /home/***/cuttag --fasta $GRCh38_genome --gtf $GRCh38_gtf --igenomes_ignore  --max_memory "150.GB"  -profile singularity --macs_gsize 2700000000 --blacklist $GRCh38_blacklist --save_merged_fastq --replicate_threshold 2 --save_reference --use_control false --spikein_fasta /home/Reference/SpikeIn/Escherichia_coli_K_12_DH10B/genome.fa  --spikein_bowtie2  /home/Reference/SpikeIn/Escherichia_coli_K_12_DH10B/Index/Bowtie2Index/ --save_spikein_aligned 

error
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:PREPARE_GENOME:BOWTIE2_BUILD_TARGET (null)'

Caused by:
  Not a valid path value type: java.util.LinkedHashMap ([id:spikein_fasta])

and there is no .command.sh file in the work dir

(nf) tree work/                                                                           
work/
├── 38
│   └── 03790fb096b186785cc31ec55bb687
├── 4a
│   └── 85055d8bd058b95142c5e7bfeb40ea
├── c6
│   └── acf9e4eb8df722a55f0cb419f313dd
├── c8
│   └── cb16441262292afffa77ee0f48a16f
├── d6
│   └── 52a0582b9a2a9f8aade79c30022117
└── tmp
    ├── 76
    │   └── 385bac3c8c2618777ee70bcfa69db7
    │       └── workflow_summary_mqc.yml
    └── b2
        └── 44901a88f4e8cf747df72ae6aab3eb
```

### Relevant files

nextflow.log file
[nextflow.log](https://github.com/nf-core/cutandrun/files/10906823/nextflow.log)

all that displayed in the shell
[error.txt](https://github.com/nf-core/cutandrun/files/10906831/error.txt)

**Comment by chris-cheshire** [comment]
Hi, would you be able to post this in the slack channels? This isn't really a bug, it could be anything! It looks like your spikein path is not valid
