### ISSUE TITLE
Error in CUSTOM_DUMPSOFTWAREVERSIONS

### ISSUE THREAD

**Issue by iagooteroc** [nf-core/cutandrun#188]
### Description of the bug

I got an error in the `NFCORE_CUTANDRUN:CUTANDRUN:CUSTOM_DUMPSOFTWAREVERSIONS` process that has to do with the versions.yml file: 
```
[Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CUSTOM_DUMPSOFTWAREVERSIONS (1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CUSTOM_DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1)
(...)
yaml.scanner.ScannerError: mapping values are not allowed here
in "versions.yml", line 17, column 18
```
The content of `versions.yml` clearly shows a problem:
```
“NFCORE_CUTANDRUN:CUTANDRUN:ALIGN_BOWTIE2:BOWTIE2_TARGET_ALIGN”:
    bowtie2: perl:
    samtools: samtools: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory
    pigz: pigz: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```
Any idea what could be causing this? I'm using singularity.

### Command used and terminal output

```console
$ nextflow run nf-core/cutandrun --input ${INPUT} --fasta ${REF} --bowtie2 ${BOWTIE2} --gtf ${GTF} --normalisation_mode 'CPM' --use_control false --dedup_target_reads --igenomes_ignore --outdir ${OUTDIR} -profile singularity
```

### Relevant files

[log_and_yml.zip](https://github.com/nf-core/cutandrun/files/11061772/log_and_yml.zip)

### System information

- Nextflow 22.10.4
- Hardware: Cluster
- Executor: slurm
- Container engine: Singularity
- OS: Rocky Linux 8.4 (Green Obsidian)
- Version of nf-core/cutandrun 3.1

**Comment by iagooteroc** [comment]
I have not encountered this problem again, so feel free to close this.

**Comment by KunFang93** [comment]
Sorry for commenting in this closed thread. I encountered the same problem. I wondered if you could shed some light on how to solve it? Thanks!

Best,
Kun
