### ISSUE TITLE
Preseq doesn't finish correctly when scratch is set

### ISSUE THREAD

**Issue by cjfields** [nf-core/cutandrun#190]
### Description of the bug

Preseq steps fail silently when `scratch` is set to a temporary space (the step appears to be optionally run, so doesn't disrupt the workflow).  This appears to be because the module is looking for the `.command.log` file, but this isn't created in the scratch folder (only in the original folder under the `work` directory). 

The fix would be to output the results to an explicit log file which is then captured for MultiQC output.

### Command used and terminal output

```console
nextflow run cutandrun -c cutnrun-yeast.conf -profile uiuc_hpcbio -qs 12 -with-report -with-trace -resume --custom_config_base /home/labs/zmadake2_lab/2023-Feb-CUTnRUN/src/configs -params-file params.yml

The workflow completes successfully but these steps fail
```

### Relevant files

`.command` output files from the run

[bug.zip](https://github.com/nf-core/cutandrun/files/11114976/bug.zip)

Execution trace:

[execution_trace_2023-03-09_23-27-12.txt](https://github.com/nf-core/cutandrun/files/11114987/execution_trace_2023-03-09_23-27-12.txt)

Config and params file:
[setup.zip](https://github.com/nf-core/cutandrun/files/11115003/setup.zip)

### System information

Nextflow version (eg. 22.10.6)
Hardware (eg. HPC)
Executor (eg. slurm)
Container engine: (e.g. Singularity)
OS (eg. CentOS Linux)
Version of nf-core/cutandrun (eg. dev)

**Comment by cjfields** [comment]
> @cjfields fancy doing a PR for this?

I can, though I'll check on the modules channel on what the recommended/preferred path is for this as there are multiple ways to fix it.

**Comment by chris-cheshire** [comment]
no worries

**Comment by chris-cheshire** [comment]
So I originally changed this line because if preseq couldn't run because it couldn't find enough data on a failed sample or something like that, the whole pipeline would fail. So I changed the log line to make it fail silently. It seems though that the nf-core team have found a more elegant solution using nextflows ignore error functionality. I have now switched back to the nf-core version. Are you able to confirm if this fixes the scratch issue? could you run `luslab/cutandrun` `-r dev`?

**Comment by cjfields** [comment]
Hi @chris-cheshire yes it looks like that addresses it!  It looks like that step should still be left as a 'fail silently'.  The test data doesn't have enough information for lc_extrap to work correctly and it fails anyway; a quick small run with some project data had one sample error out with a message: `ERROR:  too many defects in the approximation, consider running in defect mode` (that's a new one for me).

**Comment by chris-cheshire** [comment]
But the pipeline execution still runs right? It just displayed a warning that the process failed?

**Comment by cjfields** [comment]
Yep, samples run fine. I consider this fixed
