### ISSUE TITLE
Unclear how to continue once the workflow has run.

### ISSUE THREAD

**Issue by smoe** [nf-core/cutandrun#197]
### Description of feature

Dear all,

Obviously the problem sits in front of the computer for this one, but I just happen to lack ideas / priorisations of those ideas that came up to proceed with the data we generated towards something we can publish. I thought I quickly summarize what I have understood and see where this carries the discussion. Here I am:

 * The workflow has completed successfully. IgGs are negative controls.
 * For all samples I get a gene-wise summary with the number of reads upstream, downstream and in the their body that I can read into R (*computeMatrix.mat.gz or *plotHeatmap.mat.tab) and filter for the most abundantly bound and/or most-differently bound genes.
 
The consensus_upset_plots were not generated in my run, only the folder generated. Maybe that is because of my unfortunate group sizes of 4 (untreated) vs 3 (positive) vs 3 (negative) vs 1 (overexpressed isoform 1) vs 1 (overexpressed isoform 2). 

I would proceed with a ranking of genes to my liking from the gene-wise data and then compare that ranking with transcriptomics data.  But is this something I should just go and script along? Or is there something out there that I should use and cite, which I expect to help communicating everything to our reviewers?

Is there an easy way to show a heatmap with differences between groups of samples?

Many thanks!

**Comment by chris-cheshire** [comment]
Hi @smoe, the best place to ask these questions is on our slack channels. Issues are more for bugs and feature requests. https://nf-co.re/join

**Comment by smoe** [comment]
I apologize to bother you again, @chris-cheshire , but slack does not allow me to issue a request for an invitation since I do not have a Tübingen eMail address, also I cannot contact the nf-core Workspace administrator if not having the right email address. Is there a trick?

That aside, I would just go and prepare a patch to the cut'n'run documentation that describes how to filter for genes of interest.
