### ISSUE TITLE
Incorporate spike-in normalisation for macs2 peakcalling

### ISSUE THREAD

**Issue by ClaireXinSun** [nf-core/cutandrun#200]
### Description of feature

Hi all, I am wondering what is the input for macs2 in the pipeline. From what I can see, if I choose macs2 as peakcaller, it uses the bam files, which is not normalsied by spike-in. SEACR used the bed files output from bamcoverage, which have been normalised to spike-in. Does it mean the output from MACS2 are actually skipped spike-in normalisation? Thanks.

A previous issue in MACS github give some ideas using 'bdgopt' subcommand
https://github.com/macs3-project/MACS/issues/356

**Comment by svbekaer** [comment]
Hi Claire, 
Did you get any answers on this one? 
Thanks! 
Sarah-Lee

**Comment by chris-cheshire** [comment]
I missed this somehow sprry

**Comment by olechnwin** [comment]
@chris-cheshire,
Could you please elaborate on this? I see that normalization happens at the conversion from bam to bedgraph. But how to use macs2 to call peaks with the normalized bedgraph?
It would be great if you could point me to the file where this is done. Thank you so much!
