### ISSUE TITLE
 A question about the +4 and -5 shifts

### ISSUE THREAD

**Issue by bio-lilin** [nf-core/cutandrun#203]
### Description of feature

Hi nf-core cutandrun team
I would like to ask you a question about the +4 and -5 shifts. It is important to shift the raw reads in the pre-processing step to account for the 9-bp duplication in ATAC-seq. I am confused as to whether or not to perform +4 and -5 shifts in CUT&Tag. Look forward to your feedback. Thank you very much.

**Comment by chris-cheshire** [comment]
Hi, thanks for your message. Just as a rule, this question is best asked on the nf-core slack channels. To answer your question though, no we don't shift the reads. I know that the chromap aligner does this as part of its Tn5 settings, but this is not standard practice for the other major aligners, despite it being more accurate.  This would be a good feature to add, its just never really been top of the list given that most peak callers don't work at this kind of base resolution anyway, so the shift would not affect results dramatically.

**Comment by bio-lilin** [comment]
Sorry, I'm new to GitHub and didn't know how to select the question label. Thank you for your reply. I understand this question.
