### ISSUE TITLE
scale factor

### ISSUE THREAD

**Issue by ShannonTown** [nf-core/cutandrun#206]
### Description of feature

Hi, in the previous version there's a report of scale factors calculated based on the spike-in, however, I could not find the scale factors in the results using the most recent version of nf-core cutandrun pipeline. Would you please include it or if I missed it, let me know where to find it? Thank you!

**Comment by chris-cheshire** [comment]
Hi Shannon, these questions are best asked in the Slack channel for all to see, would you be able to ask there and I can answer? Many thanks, Chris

**Comment by ShannonTown** [comment]
Thank you. I did try briefly to use the Slack channel before posting here,
but somehow I could not join. I will try again later.
