### ISSUE TITLE
error with import imp

### ISSUE THREAD

**Issue by fanying2015** [nf-core/cutandrun#213]
### Description of the bug

Hello I'm trying to run the test for cutandrun pipeline with the script: nextflow run nf-core/cutandrun -profile test,conda --<outdir>. The pipeline was working initially but stopped in the middle with the error message as shown. The pipeline was updated to the latested. Any suggestions how to solve it. Additional installation of imp in the env doesn't work. Thank you

### Command used and terminal output

```console
nextflow run nf-core/cutandrun -profile test,conda --out_dir
```

### Relevant files

[log_file.txt](https://github.com/nf-core/cutandrun/files/12969627/log_file.txt)

### System information

Nextflow version: version 23.10.0 build 5889
nf-core/cutandrun: '3.2'
Hardware: HPC
Executor: local
Container engine: conda

**Comment by chris-cheshire** [comment]
Hi, the pipeline does not support conda I am afraid. Please try running with a container engine like docker or singularity.
