### ISSUE TITLE
Restricting or sorting deeptools plotprofile and heatmap by genes/gene expression

### ISSUE THREAD

**Issue by KinseyFisher** [nf-core/cutandrun#218]
Hi,
  I have processed my cut&run data using this pipeline. I want to see if genes that are up or down in an RNA-seq dataset show different profiles in the deeptools plotprofile/heatmap for H3k4me3 cut&run. To do this, I was hoping to create the deeptools plot/heatmap showing only genes that are up or down in my gene expression data (filtering which genes are plotted), or sorting the heatmap by gene expression values. Does anyone know how to do this?

**Comment by chris-cheshire** [comment]
Hi, this is a question best asked in the nf-core slack channels so other people can see the respones. 

You dont have up or down in the output for the CUT&RUN sites, this is differential analysis which is an additional analysis step. If you just want to map your up/down from RNA into the CUT&RUN sites then this is again quite complex as you need to map the sites to the genes. All together, this is not a simple question and outside the scope of what I can support im afraid. I suggest you contact a bioinformatition to help you with the code needed to perform this analysis.
