### ISSUE TITLE
ERROR ~ ERROR: Please check input samplesheet

### ISSUE THREAD

**Issue by martinezvbs** [nf-core/cutandrun#223]
### Description of the bug

Hello, 
This is my first time using nf-core/cutandrun, but I have been using before RNA-seq and ATAC-seq (both nf-core). In this case, I am using a ._csv_ file to indicate the name of the input FASTQ files, but every time that I specify it, I get the same error: **ERROR ~ ERROR: Please check input samplesheet**

Here's how I organized the .csv (I have tried both specify the whole path to the file and just the name of the file)

> group	replicate	fastq_1	fastq_2	control
> PRM_H3K4me2	1	SRR17099974_pass_1.fastq.gz	SRR17099974_pass_2.fastq.gz	PRM_IgG
> PRM_H3K4me2	2	SRR17099975_pass_1.fastq.gz	SRR17099975_pass_2.fastq.gz	PRM_IgG
> PRMK_H3K4me2	1	SRR17099976_pass_1.fastq.gz	SRR17099976_pass_2.fastq.gz	PRM_IgG
> PRMK_H3K4me2	2	SRR17099977_pass_1.fastq.gz	SRR17099977_pass_2.fastq.gz	PRM_IgG
> PRM_H3K4me3	1	SRR17099978_pass_1.fastq.gz	SRR17099978_pass_2.fastq.gz	PRM_IgG
> PRM_H3K4me3	2	SRR17099979_pass_1.fastq.gz	SRR17099979_pass_2.fastq.gz	PRM_IgG
> PRMK_H3K4me3	1	SRR17099980_pass_1.fastq.gz	SRR17099980_pass_2.fastq.gz	PRM_IgG
> PRMK_H3K4me3	2	SRR17099981_pass_1.fastq.gz	SRR17099981_pass_2.fastq.gz	PRM_IgG
> PRM_KMT2C	1	SRR17099982_pass_1.fastq.gz	SRR17099982_pass_2.fastq.gz	PRM_IgG
> PRM_KMT2C	2	SRR17099983_pass_1.fastq.gz	SRR17099983_pass_2.fastq.gz	PRM_IgG
> PRMK_KMT2C	1	SRR17099984_pass_1.fastq.gz	SRR17099984_pass_2.fastq.gz	PRM_IgG
> PRMK_KMT2C	2	SRR17099985_pass_1.fastq.gz	SRR17099985_pass_2.fastq.gz	PRM_IgG
> PRM_IgG	1	SRR17099986_pass_1.fastq.gz	SRR17099986_pass_2.fastq.gz	

### Command used and terminal output

```console
nextflow run \
    nf-core/cutandrun \
    --input path/to/directory/input/FASTQ/samplesheet_cut_n_run.csv \
    --outdir path/to/directory/results \
    --gtf /path/to/directory/reference-genomes/Mus_musculus.GRCm39.110.gtf.gz \
    --fasta path/to/directory/reference-genomes/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz \
    --blacklist /path/to/directory/reference-genomes/mm10-blacklist.v2.bed \
    --spikein_fasta path/to/directory/reference-genomes/K12_MG1655.fasta \
    --peakcaller macs2 \
    --igenomes_ignore \
    --genome null \
    --mito_name chrM \
    --remove_mitochondrial_reads true \
    --macs_gsize 1870000000 \
    --dt_calc_all_matrix false \
    -profile singularity
```

### System information

Nextflow version (23.04.2)
Hardware (HPC)
Executor (SLURM)
Container engine: (Singularity)
OS (Linux)
Version of nf-core/cutandrun (3.2.1)

**Comment by chris-cheshire** [comment]
The samplesheet should be comma seperated.

**Comment by martinezvbs** [comment]
Hi, 

Thanks for the response, the samplesheet is comma separated, the way I pasted here maybe removed the commas but the commas are there in the document. Any suggestion?
