### ISSUE TITLE
Error executing process CUTANDRUN:CUSTOM_DUMPSOFTWAREVERSIONS

### ISSUE THREAD

**Issue by ycedenocedeno** [nf-core/cutandrun#224]
### Description of the bug

I tried to run the nfcore Cut and Run pipeline but I get this Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CUSTOM_DUMPSOFTWAREVERSIONS and the pipeline goes to exit one. I don't know what it could be wrong. I checked the versions of all the programs and everything seems fine. Can someone please help me. Thank you. 

### Command used and terminal output

```console
nextflow run nf-core/cutandrun \
-params-file params.yaml \
-profile singularity \
-c nextflow.config \
```

### Relevant files

[nextflow.log](https://github.com/nf-core/cutandrun/files/13889817/nextflow.log)

### System information

Nextflow version: 23.04.4
Hardware:HPC
Executor: slurm
Container engine: Singularity
OS: CentOS Linux
Version of nf-core/cutandrun: 3.2.1

**Comment by chris-cheshire** [comment]
i need much more information here, i cant do much with what you have said, it could be anything! Can you post your params file, the console output from the error 1, describe what you are running it on etc
