### ISSUE TITLE
Missing GTF path in genome config for UCSC yeast assembly `sacCer3`

### ISSUE THREAD

**Issue by mniederhuber** [nf-core/cutandrun#225]
### Description of the bug

with `--genome sacCer3` get the following error:
```
N E X T F L O W  ~  version 23.04.2
Launching `https://github.com/nf-core/cutandrun` [tender_yalow] DSL2 - revision: 2727de382f [master]
No GTF annotation specified!
```
Checked `igenomes.conf` and It looks like there just isn't a GTF file for this assembly, or at least no path is provided. 

Runs fine with the ensemble assembly `R64-1-1`

### Command used and terminal output

```console
nextflow -log var/log/.nextflow run nf-core/cutandrun \
    -profile singularity \
    -config ~/nf-core/slurm.config \
    -params-file params.yaml
```

### Relevant files

[params.txt](https://github.com/nf-core/cutandrun/files/13890644/params.txt)

### System information

Nextflow: 23.04.2
Hardware: HPC
Executor: slurm
Container: singularity
OS: RedHat 8 x86_64
Version nf-core/cutandrun: 3.2.1

**Comment by chris-cheshire** [comment]
hi yep, there is no GTF in the igenomes setup for this right now, just grab it yourself and provide as a parameter.
