### ISSUE TITLE
don't want to skip FRiP score calculation

### ISSUE THREAD

**Issue by jdanaK** [nf-core/cutandrun#226]
Hi,
This is my first time run nf-core/cutandrun and I would like to know why FRiP score calculation was skipped with my data.
Here is my command code and I ran the nextflow with 4 samples

```nextflow
sudo nextflow run nf-core/cutandrun -profile docker --input samplesheet_test.csv --outdir ./results --genome GRCh38 --peakcaller seacr,MACS2
``` 

My teammate also ran nf-core/cutandrun with same samples at 1 year ago, and he got FRiP scores
here is his command
```nextflow
nextflow run nf-core/cutandrun --input samplesheet.csv --outdir output --genome GRCh37 -profile docker
``` 

I don't know why FRiP score calculation is skipped in my run
I tried with GRCh37 again, but it doesn't work
I'm new to informatics and Github so if more informations are needed, let me know
Thanks

the versions of my tools
Nextflow version 23.10.0
nf-core/cutandrun version 3.2.1

**Comment by chris-cheshire** [comment]
Hi thanks for your message, if you could repost this message in the nf-core slack channel that would be great. Could you post your sample sheet as well so I can debug

**Comment by RnapolyMerase1212** [comment]
Hello @jdanaK, just checking if you managed to address this issue? I just ran into the same issue, and I'm not seeing the FRiP section in my MultiQC report. Thank you for your help!
