### ISSUE TITLE
Error on the test run 

### ISSUE THREAD

**Issue by elissonnog** [nf-core/cutandrun#234]
### Description of the bug

The test is not even completely anymore. I already reinstalled it a few times. 

This is the error:

ERROR ~ Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:INPUT_CHECK:SAMPLESHEET_CHECK'

Caused by:
 Failed to pull singularity image
 command: singularity pull --name quay.io-biocontainers-python-3.8.3.img.pulling.1711660889926 docker://quay.io/biocontainers/python:3.8.3 > /dev/null
 status : 255
 message:
  INFO:  Converting OCI blobs to SIF format
  INFO:  Starting build...
  Getting image source signatures
 .
.
.
  FATAL:  While making image from oci registry: error fetching image to cache: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack layer: unpack entry: bin: restore parent directory: restore xattr metadata: /temp/build-temp-977381837/rootfs: unpriv.lsetxattr: invalid argument

 -- Check '.nextflow.log' file for details

**Comment by chris-cheshire** [comment]
Hi sorry for the delay, this is not really a good error report. I cant tell anything from this without your posting more information. If you could repost this in the slack channels for nf-core with a more complete report, that would be great

**Comment by elissonnog** [comment]
I did that and I figured out using slack.

**Comment by chris-cheshire** [comment]
nice one!
