### ISSUE TITLE
Consider changing samplesheet format to that of the ChIP-seq pipeline

### ISSUE THREAD

**Issue by j-andrews7** [nf-core/cutandrun#53]
## Is your feature request related to a problem? Please describe

In short, the samplesheet as it currently stands is somewhat confusing for new users to utilize and needlessly complicated. It also results in IgG output filenames being hardcoded, which is generally annoying.

## Describe the solution you'd like

Switching to use a more consistent and simple samplesheet like the [ChIP-seq pipeline](https://github.com/nf-core/chipseq/blob/dev/docs/usage.md#multiple-runs-of-the-same-library) may be worth consideration, as it's generally more intuitive and flexible.

**Comment by chris-cheshire** [comment]
Hi @j-andrews7 this has been implemented in v2.0
