### ISSUE TITLE
Add additional options for peak callers

### ISSUE THREAD

**Issue by j-andrews7** [nf-core/cutandrun#62]
## Is your feature request related to a problem? Please describe

SEACR has limited parameters to play with to adjust peak calling. It tends to be overly sensitive in our hands, and it has no good metrics for downstream peak filtering,

## Describe the solution you'd like

Additional options for peakcallers (MACS, MACS2, etc) would be appreciated and allow for consensus and thresholding approaches to deal with false positives downstream. Being able to run more than one peakcaller would be an added bonus.

**Comment by chris-cheshire** [comment]
Hi @j-andrews7 , we have added MACS2 as an additional peak caller in v2.0
