### ISSUE TITLE
How to skip the spike-in

### ISSUE THREAD

**Issue by blowinthesleep** [nf-core/cutandrun#73]
Hello, I'm the beginner of the nf-core framework. 
In my experiment, there is no spike-in control. But I want to use the cutandrun to analysis my data. Found no option to skip the spike-in in pipeline.

**Comment by chris-cheshire** [comment]
Hi, thanks for your message. The default spike-in is the ecoli DNA that is a natural by-product of mnase or Tn5 production. Did you explicitly remove the spike-in from your samples? If not, then you will have ecoli DNA in your samples that the pipeline will use. If you did explicitly remove this DNA and you did not spike it back in, then this is something currently unsupported in the pipeline as it Is not a recommended way to perform CUT&RUN experiments.

**Comment by chris-cheshire** [comment]
Implemented in v2.0
