### ISSUE TITLE
Missing chromosome sizes in genome.fa.sizes

### ISSUE THREAD

**Issue by HeyLifeHD** [nf-core/cutandrun#90]
### Description of the bug

Dear nf-core team,

When running the nf-core/cutandrun pipeline via singularity I am running into an error during the UCSC_BEDCLIP process. 
It states the  " Chromosome chr17 isn't in genome.fa.sizes line 94596 of igg_R1.sorted.bedGraph: chr17:75974-76048". This is confirmed when checking the genome.fa.sizes file in the working directory. It only contains chr1-16.

Thanks in advance for your support.

Best wishes,

Joschka

### Command used and terminal output

```console
export NXF_HOME=/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7
nextflow run nf-core/cutandrun \
    -resume -profile singularity \
    -c cutandrun.config \
    -r 1.1 \
    --input samplesheet.csv \
    --genome hg19 \
    --outdir /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7 \
    --email j.hey@dkfz.de 

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:UCSC_BEDCLIP (igg_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:UCSC_BEDCLIP (igg_R1)` terminated with an error exit status (255)

Command executed:

  bedClip \
      igg_R1.sorted.bedGraph \
      genome.fa.sizes \
      igg_R1.clipped.bedGraph
  
  cat <<-END_VERSIONS > versions.yml
  UCSC_BEDCLIP:
      ucsc: $(echo 377)
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: While bind mounting '/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7:/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7': destination is already in the mount point list
  WARNING: While bind mounting '/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/work/5d/b324fb0c20d7b1ba4ec31634e6bfd2:/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/work/5d/b324fb0c20d7b1ba4ec31634e6bfd2': destination is already in the mount point list
  Chromosome chr17 isn't in genome.fa.sizes line 94596 of igg_R1.sorted.bedGraph: chr17:75974-76048

Work dir:
  /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/work/5d/b324fb0c20d7b1ba4ec31634e6bfd2

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`


Pulling Singularity image docker://luslab/cutandrun-dev-plot-consensus-peaks:latest [cache /omics/groups/OE0219/internal/Joschka/singularity/cache/luslab-cutandrun-dev-plot-consensus-peaks-latest.img]
-[nf-core/cutandrun] Sent summary e-mail to j.hey@dkfz.de (sendmail)-
-[nf-core/cutandrun] Pipeline completed with errors-
WARN: Killing pending tasks (4)
```

### Relevant files

chrM    16571
chr1    249250621
chr2    243199373
chr3    198022430
chr4    191154276
chr5    180915260
chr6    171115067
chr7    159138663
chr8    146364022
chr9    141213431
chr10   135534747
chr11   135006516
chr12   133851895
chr13   115169878
chr14   107349540
chr15   102531392
chr16   52015733

### System information

N E X T F L O W  ~  version 21.10.6
Launching `nf-core/cutandrun` [grave_davinci] - revision: c30a37fd57 [1.1]

Core Nextflow options
  revision                  : 1.1
  runName                   : grave_davinci
  containerEngine           : singularity
  launchDir                 : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7
  workDir                   : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/work
  projectDir                : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/assets/nf-core/cutandrun
  userName                  : heyj
  profile                   : singularity
  configFiles               : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/assets/nf-core/cutandrun/nextflow.config, /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/cutandrun.config

Input/output options
  input                     : samplesheet.csv
  outdir                    : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7
  email                     : 

Reference data options
  genome                    : hg19
  bowtie2                   : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/
  gtf                       : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
  blacklist                 : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/assets/nf-core/cutandrun/assets/blacklists/hg19-blacklist.bed
  spikein_bowtie2           : s3://ngi-igenomes/igenomes//Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/Bowtie2Index/
  spikein_fasta             : s3://ngi-igenomes/igenomes//Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/WholeGenomeFasta/genome.fa
  fasta                     : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
  igenomes_base             : s3://ngi-igenomes/igenomes/

Pipeline Options
  gene_bed                  : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.bed

Institutional config options
  config_profile_description: ODCF cluster.
  config_profile_contact    : Joschka Hey
  config_profile_url        : https://www.dkfz.de/

Input/output options
  input                     : samplesheet.csv
  outdir                    : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7
  email                     : j.hey@dkfz.de

Reference data options
  genome                    : hg19
  bowtie2                   : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/
  gtf                       : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
  blacklist                 : /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/assets/nf-core/cutandrun/assets/blacklists/hg19-blacklist.bed
  spikein_bowtie2           : s3://ngi-igenomes/igenomes//Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/Bowtie2Index/
  spikein_fasta             : s3://ngi-igenomes/igenomes//Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/WholeGenomeFasta/genome.fa
  fasta                     : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
  igenomes_base             : s3://ngi-igenomes/igenomes/

Pipeline Options
  gene_bed                  : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.bed

Institutional config options
  config_profile_description: ODCF cluster.
  config_profile_contact    : Joschka Hey
  config_profile_url        : https://www.dkfz.de/

Max job request options
  max_cpus                  : 128
  max_memory                : 150 GB
  max_time                  : 2d

**Comment by chris-cheshire** [comment]
Hi @HeyLifeHD thanks for your message. This is very weird - the genome is automatically downloaded from igenomes, I will raise it with them and see what they say. Any reason you are not using hg38? If you are not tied to hg19, I would just run with the newer genome instead.

**Comment by chris-cheshire** [comment]
I just downloaded the genome and got 

```
chrM	16571
chr1	249250621
chr2	243199373
chr3	198022430
chr4	191154276
chr5	180915260
chr6	171115067
chr7	159138663
chr8	146364022
chr9	141213431
chr10	135534747
chr11	135006516
chr12	133851895
chr13	115169878
chr14	107349540
chr15	102531392
chr16	90354753
chr17	81195210
chr18	78077248
chr19	59128983
chr20	63025520
chr21	48129895
chr22	51304566
chrX	155270560
chrY	59373566
```

**Comment by HeyLifeHD** [comment]
Hi @chris-cheshire, i thought the same but even after deleting the ch.sizes file the error reoccurred. Sadly I am limited to hg38 due to an long term ongoing project.

**Comment by chris-cheshire** [comment]
do you mind finding the genome.fa.fai file and running 

```
cut -f 1,2 genome.fa.fai
```

**Comment by chris-cheshire** [comment]
It will be in the workfolder for `CUSTOM_GETCHROMSIZES`

**Comment by chris-cheshire** [comment]
Hey I just ran the test pipeline on our cluster for hg19 and it came back with the correct number of chromosomes - could you post your run command for the pipeline please?

**Comment by HeyLifeHD** [comment]
I will run the commands in a second when I am back at my computer. For the moment here is the command:
`export NXF_HOME=/omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7
nextflow run nf-core/cutandrun \
    -resume -profile singularity \
    -c cutandrun.config \
    -r 1.1 \
    --input samplesheet.csv \
    --genome hg19 \
    --outdir /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7 \
    --email j.hey@dkfz.de`
 I will provide the config in a minute, also no pipeline specific options were specified  besides the igenomes.

**Comment by chris-cheshire** [comment]
thanks

**Comment by HeyLifeHD** [comment]
The cutandrun.config file:
`//Profile config names for nf-core/configs
params {
  config_profile_description = 'ODCF cluster.'
  config_profile_contact = 'Joschka Hey'
  config_profile_url = 'https://www.dkfz.de/'
  max_memory=150.GB
  max_cpus=128
  max_time = 48.h


  container = 'nfcore/cutandrun:v1.1'

  //to keep negative controls
  igenomes_base = 's3://ngi-igenomes/igenomes/'

  //genomes {
  //  "hg38" {
  //            fasta = "/omics/groups/OE0219/internal/Valentin/genomes/references/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta"
  //                    gtf = "/omics/groups/OE0219/internal/Valentin/genomes/references/Homo_sapiens/GATK/GRCh38/gencode.v39.annotation.gtf.gz"
  //   }
  //}
  // genome = "hg38"
}


singularity {
  enabled = true
  cacheDir = '/omics/groups/OE0219/internal/Joschka/singularity/cache/'
  autoMounts = true
}

process {
  executor = 'lsf'
  submitRateLimit = '5 sec'

  queue = {task.time <= 10.m ? 'short' : task.time <= 1.h ? 'medium' : task.time <= 10.h ? 'long' : 'verylong'}
  errorStrategy = 'retry'
  maxRetries = 5
  perJobMemLimit=150.GB
}

plugins {
        id 'nf-amazon'
}
`
I wasn't able to find CUSTOM_GETCHROMSIZES.  I only found one genome.fa.fai in a different work directory:
 cut -f 1,2 /omics/groups/OE0219/internal/AML712_ipsc/210130_ACT_seq_nf_processing/14D7/work/f1/166befef5a3eea995fba5023351aff/genome.fa.fai
chr     4639675

**Comment by HeyLifeHD** [comment]
Regarding the genome.fa file, I don't think the reference genome for alignment was causing any problems because the input bedgraph file included chr17 alignments.

**Comment by chris-cheshire** [comment]
This is really odd - i just ran my test pipeline with exactly the same genome and it showed a normal set of chromosomes. When you run the pipeline, look for the process `CUSTOM_GETCHROMSIZES` in the log and follow it to the work directory location displayed on the left 

![image](https://user-images.githubusercontent.com/2357039/151989920-7733e30f-be5b-4e21-a8bc-aff31664b25d.png)

**Comment by HeyLifeHD** [comment]
Thanks for taking a look yourself. I will rerun the pipeline in a fresh directory and see if I can reproduce the error or if it was just some strange one-time event. My test runs with the hg38 genome worked like a charm, but I accidentally removed the old working directory.....
Best,

Joschka
