### ISSUE TITLE
fail at FRIP calculation

### ISSUE THREAD

**Issue by yinshiyi** [nf-core/cutandrun#91]
### Description of the bug

![Screenshot (39)](https://user-images.githubusercontent.com/38135561/152829377-d369e67e-8f70-4b12-8a9f-368b595802a0.png)
it fail consistently at FRIP calculation
How can i skip this step to get the multiQC steps.

Thank you

### Command used and terminal output

```console
nextflow run ./cutandrun     \
    -profile docker    \
    --input /home/shiyi/mnt/cutandrun/fastq_2022jan06/sample.csv \
    --bowtie2 /home/shiyi/mnt/2021genome/bowtie/   \
    --gtf /home/shiyi/mnt/2021genome/Sus_scrofa.Sscrofa11.1.104.gtf \
    --fasta /home/shiyi/mnt/2021genome/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa \
    --spikein_genome 'K12-MG1655' \
    --max_memory 128.GB \
    --max_cpus 70 \
    --outdir 2022_jan27_cutandrun \
    -resume special_sammet

Work well for IGV session generations
fail at FRIP calculation
```

### Relevant files

[nextflow.log.1.txt](https://github.com/nf-core/cutandrun/files/8016929/nextflow.log.1.txt)

### System information

ec2 instance

**Comment by chris-cheshire** [comment]
Thanks for your message @yinshiyi  - there is no option to skip right now but I will include as a feature in the next release scheduled before the end of feb.
